### ISSUE TITLE
Add Source Code Linking Ability to OMH Storage AAR - OUT-OF-SCOPE

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/omh-storage#153]
The current version of OMH Storage AAR lacks the ability to link the -sources.jar file with the byte code in the library. This omission prevents developers from easily navigating through the OMH source code during development and debugging. Unlike some other popular client libraries like androidx and retrofit, where source code linking is a common and beneficial feature, the absence of this capability in OMH Storage hinders efficient development and debugging workflows.

**Proposed Enhancement:**
It would be highly beneficial to include the ability to link the OMH Storage AAR with the corresponding -sources.jar file generated during library assembly. This enhancement would empower developers to:

1. Navigate seamlessly through the OMH source code while working on their projects.
2. Set breakpoints and inspect code behavior during debugging sessions without requiring manual setup steps.
3. Improve the overall development experience and productivity when integrating OMH Storage into projects.

**Benefits:**
By incorporating source code linking, OMH Storage can align with industry best practices and enhance its usability for developers. This enhancement would foster a more efficient development process, streamline debugging efforts, and ultimately contribute to a smoother integration of OMH Storage into various projects.

**Comparison to Other Libraries:**
Many well-established libraries like androidx and retrofit have successfully integrated source code linking as a standard feature. This approach has been recognized as a best practice within the development community. Incorporating a similar feature in OMH Storage would not only bring it in line with these established practices but also make it more attractive to potential users.

Thanks for considering this request.
Diego

**Comment by HectorNarvaez** [comment]
PR for update base lib on auth

(106)[https://github.com/openmobilehub/omh-auth/pull/106]

**Comment by HectorNarvaez** [comment]
PR for update auth version for modules gms, non-gms and api

[106](https://github.com/openmobilehub/omh-auth/pull/106)

**Comment by HectorNarvaez** [comment]
auth api non-gms v1.0.1-beta-> deployed on nexus ✅ 
auth api gms v1.0.1-beta -> deployed on nexus ✅ 
auth api v1.0.1-beta -> deployed on nexus ✅

**Comment by HectorNarvaez** [comment]
PR for update auth sample app

[108](https://github.com/openmobilehub/omh-auth/pull/108)

**Comment by HectorNarvaez** [comment]
Auth updated ✅

**Comment by dzuluaga** [comment]
Thanks, @HectorNarvaez. Can you please ensure also README.md and all files point to the latest version? Thanks!

**Comment by HectorNarvaez** [comment]
PR for update auth version on storage #157

**Comment by HectorNarvaez** [comment]
PR for update library versions #159

**Comment by HectorNarvaez** [comment]
storage api non-gms v1.0.8-beta -> deployed on nexus ✅ 
storage api gms v1.0.7-beta -> deployed on nexus ✅ 
storage api v1.0.5-beta -> deployed on nexus ✅

**Comment by HectorNarvaez** [comment]
PR for update library versions on sample app #160

**Comment by HectorNarvaez** [comment]
PR opened for https://github.com/openmobilehub/omh-storage/issues/153#issuecomment-1689286897

openmobilehub/omh-auth#109

**Comment by HectorNarvaez** [comment]
All changes for auth done ✅ 

All changes are on branch `1.0.1-beta`

c.c.: @dzuluaga @nelsonwilches @mariomonteroencora @teban1288

**Comment by HectorNarvaez** [comment]
PR for storage related to https://github.com/openmobilehub/omh-storage/issues/153#issuecomment-1689286897

#161

**Comment by HectorNarvaez** [comment]
All changes for storage done ✅ 

All changes are on branch `release/1.0`

c.c.: @dzuluaga @nelsonwilches @mariomonteroencora @teban1288

**Comment by HectorNarvaez** [comment]
@hans-hamel can you please comment here the changes done for maps? For have a clearer tracking about the actions done for solve this issue.

Thanks!

**Comment by dzuluaga** [comment]
Thanks @HectorNarvaez. Did you or the team get a chance to test these changes? If so, do you mind releasing them from staging? Thanks

**Comment by HectorNarvaez** [comment]
we tested it from development side. @neiger can you please help us with the QA tests? thanks!

**Comment by neiger** [comment]
@HectorNarvaez I did a smoke testing on the sample app and it looks good to me.

**Comment by HectorNarvaez** [comment]
@dzuluaga QA tested completed ✅ 

Feel free to promote the artifacts from staging to prod

c.c.: @nelsonwilches @mariomonteroencora @teban1288

**Comment by dzuluaga** [comment]
LGTM. Merged to main.
